# Generated by Django 5.0.6 on 2024-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
    ]
